services:
  go-api:
    build: .
    ports:
      - "8081:8081"
    restart: always # This tells Docker to keep it alive even if the VPS reboots
    environment:
      # This tells Go how to connect to the db service
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db # Ensures the database starts before the API
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Caps the log file at 10 Megabytes
        max-file: "3" # Keeps only the 3 most recent files

  db:
    image: postgres:15-alpine # A lightweight, official Postgres image
    restart: always
    environment:
      # These set up the database credentials automatically
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data # This saves your data so it isn't deleted on restart

volumes:
  pgdata: # Declares the persistent storage volume
