name: Deploy API to VPS

# This tells GitHub to run this script ONLY when code is pushed to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  # --- JOB 1: CONTINUOUS INTEGRATION (TESTING) ---
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # This pulls your code into GitHub runner

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26" # Matches your VPS Go version

      - name: Download Dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test -v ./.. # Runs all test in your project

  # --- JOB 2: CONTINUOUS DEPLOYMENT ---
  deploy:
    name: Deploy to Production
    needs: test # CRITICAL: This tells GitHub to wait for the 'test' job to finish successfully
    runs-on: ubuntu-latest # GitHub spins up a temporary Linux runner

    steps:
      - name: Execute deployment commands via SSH
        uses: appleboy/ssh-action@v1.0.3 # A trusted, widely-used community action for SSH
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # These are the exact commands excecuted on your VPS
            cd ~/projects/simple-go-api
            git pull origin main
            docker compose up -d --build go-api
            docker image prune -f
